version: '3'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - .:/app
    restart: always
    environment:
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=5
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    networks:
      - streamlit_network

networks:
  streamlit_network:
    driver: bridge 